feat(prisma-sample): Add Prisma example
jmcdo29/testing-nestjs pull request #1379
Opened 2021-06-25 17:22 UTC by tak1n

This adds examples on how to test a NestJS application which leverages Prisma as ORM of choice.

Closes #1268

2021-06-25 17:32 UTC, jmcdo29 requested changes
Overall the changes and the sample is looking pretty good. I do have some comments and requests, but thank you so much for making this in the first place! It's been on my radar and I just haven't had the time for it

2021-06-25 17:32 UTC, jmcdo29 commented on apps/prisma-sample/src/cat/cat.service.spec.ts
> +  });
Instead of using `overrideProvider` here, can we set up `PrismaService` as a custom provider?
```suggestion
  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CatsService,
        {
          provide: PrismaService,
          useValue: db,
      ],
    })
      .compile();

    service = module.get<CatService>(CatService);
    prisma = module.get<PrismaService>(PrismaService);
  });
```

2021-06-25 17:32 UTC, jmcdo29 commented on apps/prisma-sample/src/cat/cat.service.ts
> +    if (!cat) throw new NotFoundException('Cat not found');
I'd prefer if this wasn't an inline if, I find it more readable with the brackets, but that's a style issue and not something critical.

2021-06-25 17:32 UTC, jmcdo29 commented on apps/prisma-sample/src/prisma.module.ts
> +  provide: 'PrismaClient',
If we're gonna use a string here, can we create a constant in a `prisma.constants.ts` file? 

```ts
export const PrismaClient = 'PrismaClient'
```
And then we can `@Inject(PrismaClient)` where necessary?

What's actually the reason for this module? It looks like in the `CatsModule` you're providing a specific `PrismaService` that's unrelated to this module

2021-06-25 17:32 UTC, jmcdo29 commented on docker-compose.yml
> +      - '5432:5432'
This won't collide with the `typeorm-postgres` will it? They look to be on the same host port

2021-06-25 17:34 UTC, tak1n commented on docker-compose.yml
> +      - '5432:5432'
It will yes, just figured that out.

Question is how do we want to handle different example apps which reuse the same database? Also for prisma we would need to run `npx prisma migrate deploy` before running `npm run test:e2e`.

2021-06-25 17:44 UTC, tak1n commented on apps/prisma-sample/src/prisma.module.ts
> +  provide: 'PrismaClient',
Right, seems unnecessary, just copy pasted that part over from an application I work on in my company 😄 .

Not sure how that even works out. We thought we define PrismaModule as a global module so every other module can use `PrismaService`.

2021-06-25 17:46 UTC, jmcdo29 commented on docker-compose.yml
> +      - '5432:5432'
I think with the typeorm repo I'm using `sync: true` to auto gen it. With prisma, we could make the `test:e2e` script take care of running `prisma migrate deploy` so that it sets up the database properly.

We can also bind to a different host port for the postgres instance so that they are separate databases but use the same driver. Or we can try to go with the separate schema route, and manage multiple schemas inside a single database. I kinda like the multiple instances better, but that's me

2021-06-25 17:49 UTC, jmcdo29 commented on apps/prisma-sample/src/prisma.module.ts
> +  provide: 'PrismaClient',
If you use the module and want to use the service from it, you'd need to use `@Inject('PrismaClient')` at the moment. By providing `PrismaService` in the `CatsModule`, you're actually telling Nest to make another instance of the `PrismaServiec` which is probably opening another database connection.

2021-06-25 18:03 UTC, tak1n commented on apps/prisma-sample/src/prisma.module.ts
> +  provide: 'PrismaClient',
Hmm I see, will change it accordingly to use `PrismaClient` through `@Inject` and `prisma.constants.ts`.

2021-06-25 18:25 UTC, tak1n commented on apps/prisma-sample/src/prisma.module.ts
> +  provide: 'PrismaClient',
@jmcdo29 I wasn't really able to get it running with the custom injection token. So I just exported `PrismaService` in the global `PrismaModule` which should work as well right?

Maybe I need to revisit the NestJS docs 😅

2021-06-25 18:30 UTC, jmcdo29 commented on apps/prisma-sample/src/prisma.module.ts
> +  provide: 'PrismaClient',
Yes, that works just as well

2021-06-25 18:30 UTC, tak1n commented on docker-compose.yml
> +      - '5432:5432'
The problem with adding it to the npm command is that even with passing `--schema` as proper path it will error out because the `.env` file is in `apps/prisma-sample`, I mean I can do the following in the npm command:

- `cd apps/prisma-sample`
- `npx prisma migrate deploy`
- `cd ../..`

Let me know which route you want to go here.

2021-06-25 18:32 UTC, jmcdo29 commented on docker-compose.yml
> +      - '5432:5432'
Oh, right, cause nest monorepos are single package.jsons. Sorry, been working with pnpm workspaces and nx recently. You can probably make a shell script to cd into the sample, run the migration, and cd back to main as a pre e2e script kind of setup

2021-06-25 18:45 UTC, tak1n commented
@jmcdo29 we also have to set `DATABASE_URL` for the e2e tests of prisma-sample as it didn't commit the .env file (most likely in .gitignore like it should be). I will just add it to the npm command if thats fine for you?

2021-06-25 18:46 UTC, jmcdo29 commented
Yeah, adding it to the npm command sounds good here.

2021-06-25 19:05 UTC, tak1n commented
```
> testing-nestjs@0.0.1 test /home/runner/work/testing-nestjs/testing-nestjs
> jest "prisma-sample"

FAIL apps/prisma-sample/src/cat/cat.controller.spec.ts
  ● Test suite failed to run

    apps/prisma-sample/src/cat/cat.controller.ts:12:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Cat'.

    12 import { Cat } from '@prisma/client';
                ~~~

FAIL apps/prisma-sample/src/cat/cat.service.spec.ts
  ● Test suite failed to run

    apps/prisma-sample/src/cat/cat.service.ts:3:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Cat'.

    3 import { Cat } from '@prisma/client';
               ~~~

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        5.827 s
```

Weirdly it succeeds for me locally. Maybe we need to run `npx prisma generate` manually before unit tests, so it generates the proper client and types for it - https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/install-prisma-client-typescript-postgres 🤔

2021-06-25 19:05 UTC, tak1n commented
> ```
> > testing-nestjs@0.0.1 test /home/runner/work/testing-nestjs/testing-nestjs
> > jest "prisma-sample"
> 
> FAIL apps/prisma-sample/src/cat/cat.controller.spec.ts
>   ● Test suite failed to run
> 
>     apps/prisma-sample/src/cat/cat.controller.ts:12:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Cat'.
> 
>     12 import { Cat } from '@prisma/client';
>                 ~~~
> 
> FAIL apps/prisma-sample/src/cat/cat.service.spec.ts
>   ● Test suite failed to run
> 
>     apps/prisma-sample/src/cat/cat.service.ts:3:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Cat'.
> 
>     3 import { Cat } from '@prisma/client';
>                ~~~
> 
> Test Suites: 2 failed, 2 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        5.827 s
> ```
> 
> Weirdly it succeeds for me locally. Maybe we need to run `npx prisma generate` manually before unit tests, so it generates the proper client and types for it - https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/install-prisma-client-typescript-postgres

Here is the reason:
```
prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma schema file yet, you can ignore this message.
```

2021-06-25 19:06 UTC, jmcdo29 commented
Yeah, I could see it needing a way to generate those types so that typescript and `ts-jest` don't get confused on them. Kinda sucks that a unit test is going to have to depend on the database, but I guess that's prisma

2021-06-25 19:08 UTC, tak1n commented
> Yeah, I could see it needing a way to generate those types so that typescript and `ts-jest` don't get confused on them. Kinda sucks that a unit test is going to have to depend on the database, but I guess that's prisma

Yea its not really hard depending on the database here, just that the client is generated from the schema file. So we still don't need a real db for this setup step, afaik.

2021-06-27 16:09 UTC, jmcdo29 commented
Looks like before the e2e test we need to run the interface generation again. Add that and I think this will be perfect

2021-06-28 06:45 UTC, tak1n commented
@jmcdo29 think with the latest commit the e2e tests as well the coverage run should work, I still dislike the fact that we had to adapt npm commands which are used across sub repos just for prisma usage, but if you are fine with that fine for me as well ✌🏽

In my day to day work with prisma its usually fine, as we are not using a monorepo with multiple services which use different ORMs/Databases.

2021-06-28 06:51 UTC, jmcdo29 commented
Thanks for all your work on this! Looks like it's all passing to me so I'm happy to get this merged!

2021-06-28 06:51 UTC, merged