tests(sequelize-sample): update unit tests
jmcdo29/testing-nestjs pull request #1450
Opened 2021-09-07 10:24 UTC by Tony133

Update unit tests for sequelize

P.s. Thanks for the help on testing 🙌

2021-09-21 19:06 UTC, jmcdo29 requested changes
Made a few comments. Overall looks good. Address the changes and I'll consider it good to go

2021-09-21 19:06 UTC, jmcdo29 commented on apps/sequelize-sample/src/cats/cats.controller.spec.ts
> +  });
These should both be async, and the controller calls should be `await`ed

2021-09-21 19:06 UTC, jmcdo29 commented on apps/sequelize-sample/src/cats/cats.service.spec.ts
> +  });
Lets do something like
```suggestion
  it('should remove a cat', async () => {
    const destroyStub = jest.fn();
    const findSpy = jest.spyOn(model, 'findOne').mockReturnValue({
      destroy: destroyStub
    } as any);
    const retVal = await service.removeCat('id');
    expect(findSpy).toBeCalledWith({ where: { id: 'id' } });
    expect(destroyStub).toBeCalledTimes(1);
    expect(retVal).toBeUndefined();
  });
```
To assert that this flow works as expected

2021-09-22 15:05 UTC, Tony133 commented on apps/sequelize-sample/src/cats/cats.controller.spec.ts
> +  });
Yeah, you know maybe I missed this part 😄, anyway I made a commit for it. 👀

2021-09-22 15:07 UTC, Tony133 commented on apps/sequelize-sample/src/cats/cats.service.spec.ts
> +  });
Ok 👍

2021-09-22 15:11 UTC, Tony133 commented
Let me know if you find other parts to improve  👀👍

2021-09-22 15:12 UTC, jmcdo29 approved these changes
LGTM

2021-10-04 20:16 UTC, Tony133 commented
Hi @jmcdo29 , when you find some time can you merge this pull? or something is missing to fix? 👀

2021-10-04 20:33 UTC, merged