feat(): added http sample
jmcdo29/testing-nestjs pull request #1478
Opened 2021-10-04 14:39 UTC by Tony133

Hi @jmcdo29 😀👋 I created an example for using HttpModule as I told you.
The only part of the tests that I have many doubts is that of the `cats.service.spec.ts`, do you have any idea how to do them? I tried to do them as you can see but the test is not passed in the create and in the update it gives me this error `TypeError: specificMockImpl.apply is not a functionJest`.😫

There must be something I missed 👀, however let me know what you think, feel free to write me about Discord 🙌

2021-12-10 22:55 UTC, jmcdo29 commented
Implementation of the test looks much better. Fix up the merge conflicts and I think this will be good to merge

2021-12-11 11:44 UTC, Tony133 commented
Hi @jmcdo29, when you find some time you can resolve these conflicts (see screenshot), as I don't have the permissions.
<img width="829" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/145675232-30bb0f94-79cd-4744-ab29-e4e6f5d57110.png">

2021-12-11 17:28 UTC, jmcdo29 commented
> Hi @jmcdo29, when you find some time you can resolve these conflicts (see screenshot), as I don't have the permissions. 

@Tony133 You should be able to `git pull --rebase origin master` and resolve the merge conflicts locally. Then force push back up to your branch after you resolve everything. The message GitHub is showing is that you don't have permissions to merge the Pull Request

2021-12-11 17:34 UTC, Tony133 commented
Ok I try, I usually solved them via the resolve conflicts button

2021-12-11 17:51 UTC, Tony133 commented
@jmcdo29 i resolved conflicts with other git commands, but check if everything went ok.

2021-12-11 18:00 UTC, jmcdo29 requested changes
Saw a few more things I should've called out a while ago

2021-12-11 18:03 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
```suggestion
  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should get the cats', () => {
    expect(await controller.findAll()).toEqual([testCat]);
  });

  it('should get one cat', () => {
    expect(await controller.findOne('a id')).toEqual(testCat);
  });

  it('should make a new cat', () => {
    expect(
      await controller.create({
        name: 'Test Cat',
        age: 5,
        breed: 'Russian Blue',
      }),
    ).toEqual(testCat);
  });

  it('should remove a one cat', () => {
    const retVal = controller.remove('a id');
    expect(service.remove).toHaveBeenCalled();
    expect(retVal);
  });
```

2021-12-11 19:49 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.ts
> +}
we have to do something like this:
```
  @Get()
  async findAll(): Observable {
    return await this.catsService.findAll();
  }
```
?

2021-12-11 20:44 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
I remove both `async` and `await` but also `Observable` must be inserted in the tests?

2021-12-11 21:02 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.ts
> +}
```ts
@Get()
findAll(): Observable<Cat[]> {
  return this.catsService.findAll();
}
```

No `async` or `await` because we aren't using promises anywhere with the HttpService

2021-12-11 21:25 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.ts
> +}
it works like this otherwise it gives me an error:
```
  @Get()
  findAll(): Observable<AxiosResponse<Cat[]>> {
    return this.catsService.findAll();
  }
```

2021-12-11 21:48 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.ts
> +}
Done!

2021-12-11 21:57 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Done!

2021-12-11 21:59 UTC, Tony133 commented
I think that even in the `cats.service.spec.ts` I have to remove the `async` and `wait` right?

2021-12-11 23:57 UTC, jmcdo29 commented
Looks like there's two types for axios installed. We need to make sure only one is used

2021-12-12 16:00 UTC, Tony133 commented
Only one test fails for this:

<img width="1313" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/145719496-c115fc0f-21a3-42e9-ba51-a911fb32aecf.png">

some idea?

2021-12-12 16:48 UTC, jmcdo29 commented
> Only one test fails for this:
> 
> <img alt="screenshot" width="1313" src="https://user-images.githubusercontent.com/11542387/145719496-c115fc0f-21a3-42e9-ba51-a911fb32aecf.png">
> 
> some idea?

[Like I just said here](https://github.com/jmcdo29/testing-nestjs/pull/1478#issuecomment-991806788) there's two instances of axios installed and the types are clashing

2021-12-12 17:07 UTC, Tony133 commented
I tried removing and reinstalling the dependencies regarding axios, let's see if it still gives the error

2021-12-12 17:11 UTC, Tony133 commented
Ok, before it was a dependency installation problem and we fixed it now there is another error it should be a test error if I'm not wrong?

2021-12-12 17:16 UTC, Tony133 commented
Ok and the method `findAll` in the service:

```
  it('should return all cats', () => {
    const data = {};

    const response: AxiosResponse<any> = {
      data,
      headers: {},
      config: { url: 'http://localhost:3000/mockUrl' },
      status: 200,
      statusText: 'OK',
    };

    jest
      .spyOn(httpService, 'get')
      .mockReturnValue(of({ data: require('../../cats.json') }) as any);

    httpService.get('http://localhost:3000/mockUrl').subscribe((res) => {
      expect(res).toEqual(res);
    });
  });
```
this line here giving the error:
 ``` expect(res).toEqual(res);```

2021-12-12 17:45 UTC, jmcdo29 commented
> Ok and the method `findAll` in the service:
> 
> ```
>   it('should return all cats', () => {
>     const data = {};
> 
>     const response: AxiosResponse<any> = {
>       data,
>       headers: {},
>       config: { url: 'http://localhost:3000/mockUrl' },
>       status: 200,
>       statusText: 'OK',
>     };
> 
>     jest
>       .spyOn(httpService, 'get')
>       .mockReturnValue(of({ data: require('../../cats.json') }) as any);
> 
>     httpService.get('http://localhost:3000/mockUrl').subscribe((res) => {
>       expect(res).toEqual(res);
>     });
>   });
> ```
> 
> this line here giving the error: ` expect(res).toEqual(res);`

What is this even testing? I'm surprised `expect(res).toEqual(res)` is giving an error, but what is that trying to test in the first place?

2021-12-12 20:26 UTC, Tony133 commented
sorry, this was the code I meant:
```
  it('should return all cats', () => {
    const data = {};

    const response: AxiosResponse<any> = {
      data,
      headers: {},
      config: { url: 'http://localhost:3000/mockUrl' },
      status: 200,
      statusText: 'OK',
    };

    jest
      .spyOn(httpService, 'get')
      .mockReturnValue(of({ data: require('../../cats.json') }) as any);

    httpService.get('http://localhost:3000/mockUrl').subscribe((res) => {
      expect(res).toEqual(response);
    });
  });

```

i put what i was trying i to fix it.

2021-12-12 21:31 UTC, jmcdo29 commented
Why would 
```ts
 const response: AxiosResponse<any> = {
      data,
      headers: {},
      config: { url: 'http://localhost:3000/mockUrl' },
      status: 200,
      statusText: 'OK',
    };
```
be the same as 
```ts
{ data: require('../../cats.json') }
```
?

2021-12-12 21:55 UTC, Tony133 commented
I did a bit 'of confusion.

2021-12-12 22:01 UTC, Tony133 commented
If you have any ideas how to fix let me know at the moment I run out of ideas

2021-12-14 22:11 UTC, Tony133 commented
nothing continues to fail despite the drive test passing

<img width="1359" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/146087433-3828d95b-1c8a-43a7-8fce-9d734fe14ef5.png">

2021-12-14 22:29 UTC, Tony133 commented
They have passed! 🙌

2021-12-14 22:47 UTC, jmcdo29 requested changes
Saw a few more things that I missed before

2021-12-14 22:47 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +        CatsService,
```suggestion
```

2021-12-14 22:47 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +        CatsService,
No reason to have this, you're mocking it on the next line

2021-12-14 22:47 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
Usually, these should be matching what the `CatsService` would normally be returning. In this case, that means `Observables`

2021-12-14 22:47 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +  });
Why are you calling the `HttpService` directly instead of  calling the `CatsService`?

2021-12-14 22:47 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +    });
Why call the HttpService instead of the CatsService?

2021-12-14 22:47 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +    });
Same as the other two comments here

2021-12-15 09:48 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +        CatsService,
true 👍, i missed it

2021-12-15 10:04 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
Ok, but so how should this part be implemented?

2021-12-15 10:04 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +  });
Here I simulate calling on a fake URL or endpoint by calling HttpService. Now I don't know if that's right because it's my first time writing a test for it.

2021-12-15 10:04 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +    });
Here I simulate calling on a fake URL or endpoint by calling HttpService. Now I don't know if that's right because it's my first time writing a test for it.

2021-12-15 10:04 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +    });
Here I simulate calling on a fake URL or endpoint by calling HttpService. Now I don't know if that's right because it's my first time writing a test for it.

2021-12-15 16:54 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
Well, the `Controller` is returning an obsevable because the Service is returning an observable, right? So in the test, the service should still return an observable, so that the controller can follow the same pattern

2021-12-15 16:56 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +  });
You should be calling service method that ends up calling this http service method. You created an `update` method on `CatsService` that calls `this.httpService.put()` so that's what you should be calling in the test. Otherwise, you aren't testing the service code at all, you're just ensuring your mock returns what you said it should, which is testing that jest behaves the way we believe it too.

2021-12-15 16:56 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +  });
https://github.com/jmcdo29/testing-nestjs/pull/1478/files/17d3c842de5b6a2374858c79b3bae99afc86b9e7#diff-f9bd70f0c354bf1493a013454d5947bc7c07a39e6df8af5e0d8e68a620ba3f8dR32

2021-12-15 17:01 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
Yes, of course the controller returns an observable.
Such as:
  ```
@Post()
  create (@Body() createCatDto: CreateCatDto): Observable<AxiosResponse<Cat[]>> {
    return this.catsService.create(createCatDto);
  }
```

so you need to edit this part here:
```
          provide: CatsService,
          useValue: {
            findAll: jest.fn(() => [testCat]),
            findOne: jest.fn(() => testCat),
            create: jest.fn(() => testCat),
            update: jest.fn(),
            remove: jest.fn(),
          },
```
?

2021-12-15 17:02 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
Yep, the mock service should be returning an observable just like the real one does. It's just that in the test we control what the value of the data is

2021-12-15 17:19 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
So how would `findAll` become for example: `jest.fn(() => [testCat]),` ?

2021-12-15 17:21 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
`jest.fn(() => of([testCat]))`

2021-12-16 17:20 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +  });
how should this part be implemented? not understood can you give some examples?
Usually `this.httpService` is used when passing to `HttpService` constructor.

2021-12-16 17:22 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +          },
Done!

2021-12-16 17:32 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +      });
To test the service, it should be something like this:

```suggestion
  it('should return a cat update', () => {
    const data = {
      name: 'cat #1',
      age: '10',
      breed: 'Russian',
      id: 5,
    };

    const response: AxiosResponse<any> = {
      data,
      headers: {},
      config: { url: 'http://localhost:3000/mockUrl/5' },
      status: 200,
      statusText: 'OK',
    };

    jest.spyOn(httpService, 'put').mockImplementation(
      () =>
        of({
          data: {
            name: 'cat #1',
            age: '10',
            breed: 'Russian',
            id: 5,
          },
          headers: {},
          config: { url: 'http://localhost:3000/mockUrl/5' },
          status: 200,
          statusText: 'OK',
        }) as any,
    );

    service.update(5, {name: 'cat #1' }).subscribe(res => expect(res).toEqual(response.data))
  });
```

2021-12-16 17:35 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +      });
Ok I try, then I'll let you know

2021-12-16 18:11 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +    });
Resolved

2021-12-16 18:11 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +    });
Resolved!

2021-12-16 18:11 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +      });
Resolved!

2021-12-16 18:11 UTC, Tony133 commented on apps/http-sample/src/cats/cats.service.spec.ts
> +  });
Resolved!

2021-12-16 18:13 UTC, Tony133 commented
only the controller(`cats.controller.spec.ts`) does not convince me how I implemented the code, when you find some time can you take a look at it?

2021-12-16 18:15 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Why are you making observables of the controller method? `controller.method()` should already be returning an observable thanks to the mock you created above

2021-12-16 18:17 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
it gave me error and i did like this, but now it gives this error:
<img width="1254" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/146426763-7bee8883-ba59-4c72-ae63-07fac026a286.png">

2021-12-16 18:21 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Error before modification to the controller:
<img width="1019" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/146427206-a8f27d8b-cb66-4289-8d9e-845bae205d9a.png">

2021-12-16 18:21 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Did you do `controller.method(parameters).subscribe(res => expect(res).toEqual(whatever))`? This is all testing observables, every steps of the way

2021-12-16 18:23 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
before it was like this:
```
  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should get the cats', () => {
    expect(controller.findAll()).toEqual([testCat]);
  });

  it('should get one cat', () => {
    expect(controller.findOne('a id')).toEqual(testCat);
  });

  it('should make a new cat', () => {
    expect(
      controller.create({
        name: 'Test Cat',
        age: 5,
        breed: 'Russian Blue',
      }),
    ).toEqual(testCat);
  });

  it('should remove a one cat', () => {
    const retVal = controller.remove('a id');
    expect(service.remove).toHaveBeenCalled();
    expect(retVal);
  });
```

2021-12-16 18:24 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Right, so that won't work. `controller.method()` now returns an observable, just like the service methods, and need to be tested the same way

2021-12-16 20:07 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
I just have a doubt is the remove method in the controller okay? or should it be modified?

2021-12-16 20:15 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
for the remove method maybe do it like this:
 ``` 
 it('should remove a one cat', () => {
    const retVal = controller.remove('a id').subscribe((res) => {
      expect(res).toEqual(testCat);
    });
    expect(service.remove).toHaveBeenCalled();
  });
```

?

2021-12-16 20:34 UTC, jmcdo29 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Yeah, the method needs to be subscribed to so we can ensure it was all called

2021-12-16 20:43 UTC, Tony133 commented on apps/http-sample/src/cats/cats.controller.spec.ts
> +  });
Done! In this commit : [test(): updated test on method remove in controller](https://github.com/jmcdo29/testing-nestjs/pull/1478/commits/c554d4e83e567134c5ec60fa50f87e609d590ccb).

It could go well?

2021-12-16 20:46 UTC, Tony133 commented
fails a test not for this PR, you are able to start the CI again ?

2021-12-16 20:57 UTC, Tony133 commented
Tests passed! 🙌 👀

2021-12-16 21:01 UTC, Tony133 commented
Now that I think about it maybe the README is missing to add right?

2021-12-16 21:12 UTC, jmcdo29 commented
> Now that I think about it maybe the README is missing to add right?

Yep, README with an explanation of how the observables are tested and a screenshot showing the coverage

2021-12-16 21:19 UTC, Tony133 commented
coverage is not heavily covered in the service:

<img width="1002" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/146450429-47b5649c-e62c-4954-bf86-5da9d99e842a.png">

okay anyway?

2021-12-16 21:21 UTC, jmcdo29 commented
> coverage is not heavily covered in the service:
> 
> <img alt="screenshot" width="1002" src="https://user-images.githubusercontent.com/11542387/146450429-47b5649c-e62c-4954-bf86-5da9d99e842a.png">
> 
> okay anyway?

How did you generate the coverage? It looks like the `cats.service.spec.ts` wasn't ran

2021-12-16 21:27 UTC, Tony133 commented
sorry i did the cover only in the controller:
<img width="1519" alt="screenshot2" src="https://user-images.githubusercontent.com/11542387/146451329-f09a673d-64ef-406f-9e8d-898d4186629e.png">

<img width="2047" alt="screnshot1" src="https://user-images.githubusercontent.com/11542387/146451307-6f5938c9-d744-4b2b-97c4-4c269227c886.png">

2021-12-16 21:41 UTC, Tony133 commented
I created the README, let me know if it could be ok
See commit: [added README.md with coverage test picture](https://github.com/jmcdo29/testing-nestjs/pull/1478/commits/335e67d0fb56a7c7516705da6b1e38364bedd02e)

2021-12-16 22:25 UTC, jmcdo29 approved these changes

2021-12-16 22:27 UTC, jmcdo29 commented
Looks great. I'll look into getting this merged soon

2021-12-16 22:28 UTC, merged