feat(): added observable sample
jmcdo29/testing-nestjs pull request #1521
Opened 2022-01-02 22:13 UTC by Tony133

Hi @jmcdo29, first of all happy new year friend, I created this example as I think it will be useful I just have some doubts about the controller test seen it returns me a `JestAssertionError: expect (received) .toEqual (expected) // deep equality`, I had already solved this problem but I don't remember how I did it, I've been thinking about it for a few days but I couldn't solve it. 
When you find time, if you have any ideas let me know 👍

I hope then the rest can go well 🤞, let me know what you think ok? 

P.s. I saw that you converted the monorepo with Nx, fantastic! 🙌

2022-01-02 22:31 UTC, jmcdo29 requested changes

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/app.module.ts
> +    }),
Why add in TypeORM instead of using an in memory array? Each sample application should be pretty minimum to help make the example easy to understand. Adding in too many features can make the samples harder to grasp

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.ts
> +      }),
Why have this `map` operator if it's not actually mapping anything?

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/entities/cat.entity.spec.ts
> +describe('Cat class', () => {
Do we actually need to test the entity? Do we even need the entity if there's no TypeORM connection?

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/entities/cat.entity.ts
> +  }
_If_ we keep this constructor, why not do something like

```suggestion
  constructor(partial: Partial<Cat> = {}) {
    Object.assign(this, partial);
  }
```

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +          },
Why is the repository returning an observable? Shouldn't it still return a promise that the service turns into an observable?

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +  });
There should be a test for the error path

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +  });
There should be a test for the error path

2022-01-02 22:31 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +    });
Every test here should use a callback and in the `subscribe` there should be a call to the callback on complete
```suggestion
    it('should return an array of cats', (done) => {
      service.findAll().subscribe({
        next: (cats) => {
          expect(cats).toEqual(catArray);
        },
        complete: () => done()
      });
    });
```

2022-01-02 22:35 UTC, Tony133 commented on apps/observable-sample/src/app.module.ts
> +    }),
I took inspiration from the `typeorm-sample`, to make the samples at least for the connection not too different

2022-01-02 22:38 UTC, jmcdo29 commented
Also, what benefit does this bring over the existing [rxjs-sample](https://github.com/jmcdo29/testing-nestjs/tree/master/apps/rxjs-sample). The sample isn't a CRUD application, but it and the [http-sample](https://github.com/jmcdo29/testing-nestjs/tree/master/apps/http-sample) do a pretty good job of showing observable testing, right? Is there a need for this new application?

2022-01-02 22:39 UTC, Tony133 commented on apps/observable-sample/src/cat/entities/cat.entity.spec.ts
> +describe('Cat class', () => {
it depends if we want to follow the `typeorm-sample` example, then yes the entity is needed, otherwise not

2022-01-02 22:51 UTC, Tony133 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +          },
On this point I had many doubts about it, so in the service it should return a promise?

2022-01-02 22:52 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +          },
The TypeORM `Repository` returns promises. You use the `from` rxjs operator to create an observable from the promise, so the Repository does still need to return a promise to allow the service to work correctly

2022-01-02 23:01 UTC, Tony133 commented
I haven't found an example with crud using observables and with tests. I think it might be fine as an example, but I find it closer to `http-sample` than to` rxjs-sample`. As a setting

Surely it could be useful as an example for me to look at. I leave the choice to you

2022-01-02 23:03 UTC, Tony133 commented on apps/observable-sample/src/cat/entities/cat.entity.ts
> +  }
let's say the entity test is an extra

2022-01-02 23:08 UTC, Tony133 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +          },
 understood, I was convinced that doing for example:

 findOne(id: string): Observable<Cat> {..}

 in the service returned an Observable

2022-01-02 23:10 UTC, Tony133 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +          },
so this service setting is wrong?
```
@Injectable()
export class CatService {
  constructor(
    @InjectRepository(Cat) private readonly catRepository: Repository<Cat>,
  ) {}

  findAll(): Observable<Cat[]> {
    return from(this.catRepository.find()).pipe(
      map((cats: Cat[]) => {
        return cats;
      }),
    );
  }

  findOne(id: string): Observable<Cat> {
    return from(this.catRepository.findOne({ id })).pipe(
      map((cats: Cat) => {
        return cats;
      }),
    );
  }

  create(cat: CatDTO): Observable<any> {
    const newCat = new Cat();
    newCat.name = cat.name;
    newCat.breed = cat.breed;
    newCat.age = cat.age;
    return from(this.catRepository.save(newCat)).pipe(
      map((user: Cat) => {
        const { ...result } = user;
        return result;
      }),
      catchError(() => throwError(() => new Error('Cat not created!'))),
    );
  }

  update(id: string, cat: CatDTO): Observable<any> {
    return from(this.catRepository.update({ id }, cat)).pipe(
      map(() => this.findOne(id)),
      catchError(() => throwError(() => new Error('Cat not updated!'))),
    );
  }

  delete(id: string): Observable<any> {
    return from(this.catRepository.delete({ id }));
  }
}
```

2022-01-03 01:33 UTC, jmcdo29 commented
> I haven't found an example with crud using observables and with test

But what about Observables in general need to be tied to CRUD for testing purposes? I guess that's what I'm trying to get at. Once you know how to test _an_ observable (like how the rxjs or http sample do) then the same pattern should be applicable elsewhere, regardless if it's CRUD or some complex logic.

2022-01-03 01:34 UTC, jmcdo29 commented on apps/observable-sample/src/cat/cat.service.spec.ts
> +          },
The service is written fine, and the methods do return observables, but the thing you're mocking, the TypeORM repository, its methods return promises.

2022-01-03 14:24 UTC, Tony133 commented
I understand what you mean,I was wrong, sorry, I thought it could be a different test case, which could help to understand better observable during the test. 
If you want I can close this PR, let me know how to proceed, no problem for me 👍 . But when you find time, I have some things to ask you about but I am writing to you on Discord.

2022-01-03 15:53 UTC, closed without merging